# Generated by Django 4.2.2 on 2023-07-31 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_categoria_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='producto/%y/%m/%d', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='pvp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de venta'),
        ),
    ]
