# Generated by Django 4.2.4 on 2023-08-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_categoria_date_creation_categoria_date_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
    ]
