# Generated by Django 4.2.4 on 2023-09-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=150)),
                ('Identificacion', models.CharField(max_length=10, unique=True)),
                ('Direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('Telefono', models.CharField(max_length=10)),
                ('Correo', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['id'],
            },
        ),
    ]
