# Generated by Django 4.2.2 on 2023-07-04 02:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=150)),
                ('Apellidos', models.CharField(max_length=150)),
                ('Cedula', models.CharField(max_length=10, unique=True)),
                ('Cumple', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Nacimiento')),
                ('Direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('Sexo', models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino')], default='male', max_length=10)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('Cantidad', models.IntegerField(default=0)),
                ('Subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalle de Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=150, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='producto/%y/%m/%d')),
                ('pvp', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_joined', models.DateField(default=datetime.datetime.now)),
                ('Subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('Iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('Total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('Cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.cliente')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='categ',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='type',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='Nombre',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='producto',
            name='cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.categoria'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='Produ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.producto'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='Venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.venta'),
        ),
    ]
