# Generated by Django 4.2.3 on 2023-07-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_cliente_detalleventa_producto_venta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='Descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
